spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/hr_helpdesk}
      database: hr_helpdesk
  application:
    name: hr-helpdesk-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:hrHelpdeskSecretKey123456789012345678901234567890}
  expiration: 86400000

logging:
  level:
    com.hrhelpdesk: INFO
    org.springframework.data.mongodb: INFO
    org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/hr_helpdesk_dev
      database: hr_helpdesk_dev

logging:
  level:
    com.hrhelpdesk: DEBUG
    org.springframework.data.mongodb: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE:hr_helpdesk}

logging:
  level:
    root: WARN
    com.hrhelpdesk: INFO